### ISSUE TITLE
[SUGGEST] sqlite as DB

### ISSUE THREAD

**Issue by sonyarianto** [fityannugroho/idn-area#56]
This is nice, lanjutkan, but I imagine the source data also provided in sqlite data hehehe :)

**Comment by fityannugroho** [comment]
I aspire that in the future this API can support all types of databases that have connector provided by [Prisma](https://www.prisma.io/docs/concepts/database-connectors), including SQLite.

But if you mean providing a data source in the form of an SQL query, I don't think that's a good approach.

The data for this API is managed separately in [idn-area-data](https://github.com/fityannugroho/idn-area-data#motivation) that store the data sources in CSV and use JavaScript to parse it into an array. So that, you can insert the data source into any database using the right tools. 

For SQLite, you can use [sqlite3](https://www.npmjs.com/package/sqlite3) or [Prisma with SQLite connector](https://www.prisma.io/docs/concepts/database-connectors/sqlite). Of course there are many other options.

**Comment by sonyarianto** [comment]
@fityannugroho ah ic ic, just realized that the data is on seperate repo and it's CSV, even better. Great thank you.
